# Uncomment the next line to define a global platform for your project

platform :ios, '8.0'

target 'ALTimerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ALTimerDemo

pod 'ALTimer',:path => '../ALTimer/ALTimer'


end
